# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tag.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1445, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setGeometry(QtCore.QRect(90, 160, 411, 531))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(550, 200, 811, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_19.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 4, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_29.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 1, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_20.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 3, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_11.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_12.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_28.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 1, 3, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_24.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_5.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_16.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 5, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_7.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_6.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_13.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 5, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_14.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 5, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("font:18pt \"Times New Roman\";\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_9.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_2.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_23.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 2, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_18.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 4, 4, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_31.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_2.addWidget(self.pushButton_31, 0, 3, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_32.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_2.addWidget(self.pushButton_32, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_3.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_21.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 3, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_15.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 5, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_4.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_30.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_2.addWidget(self.pushButton_30, 3, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_10.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 4, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_25.setStyleSheet("font:18pt \"Times New Roman\";\n"
"\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 0, 2, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_22.setStyleSheet("font:18pt \"Times New Roman\";")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 3, 4, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(580, 730, 372, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_17.setStyleSheet("font: 28pt \"Times New Roman\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_26.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_26.setStyleSheet("font: 28pt \"Times New Roman\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 0, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(140, 30, 217, 31))
        self.pushButton_27.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(140, 80, 217, 31))
        self.pushButton_33.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 661, 31))
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("border:2px solid red;\n"
"border-color: rgb(173, 173, 173);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 80, 661, 31))
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("border:2px solid red;\n"
"border-color: rgb(173, 173, 173);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1220, 50, 81, 41))
        self.label_4.setStyleSheet("font: 15pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_19.setText(_translate("MainWindow", "Needle"))
        self.pushButton_29.setText(_translate("MainWindow", "EtroMiss"))
        self.pushButton_20.setText(_translate("MainWindow", "MESA"))
        self.pushButton_11.setText(_translate("MainWindow", "MuGoldL1"))
        self.pushButton.setText(_translate("MainWindow", "Good"))
        self.pushButton_12.setText(_translate("MainWindow", "MuGoldL4"))
        self.pushButton_28.setText(_translate("MainWindow", "EtroDirtyL1"))
        self.pushButton_24.setText(_translate("MainWindow", "EtroThinL4"))
        self.pushButton_5.setText(_translate("MainWindow", "EdgeAbnomal"))
        self.pushButton_16.setText(_translate("MainWindow", "Deelte"))
        self.pushButton_7.setText(_translate("MainWindow", "Mark"))
        self.pushButton_6.setText(_translate("MainWindow", "EtroThinL1"))
        self.pushButton_13.setText(_translate("MainWindow", "Scratch"))
        self.pushButton_14.setText(_translate("MainWindow", "TwoConnectL2"))
        self.pushButton_8.setText(_translate("MainWindow", "ColorDif"))
        self.pushButton_9.setText(_translate("MainWindow", "DarkL1"))
        self.pushButton_2.setText(_translate("MainWindow", "ITO"))
        self.pushButton_23.setText(_translate("MainWindow", "EtroThinL2"))
        self.pushButton_18.setText(_translate("MainWindow", "PV"))
        self.pushButton_31.setText(_translate("MainWindow", "DirtyL2"))
        self.pushButton_32.setText(_translate("MainWindow", "DirtyL14"))
        self.pushButton_3.setText(_translate("MainWindow", "Epitacy"))
        self.pushButton_21.setText(_translate("MainWindow", "Misalign"))
        self.pushButton_15.setText(_translate("MainWindow", "TwoConnectL4"))
        self.pushButton_4.setText(_translate("MainWindow", "EdgeDefect"))
        self.pushButton_30.setText(_translate("MainWindow", "MuGoldEtroL1"))
        self.pushButton_10.setText(_translate("MainWindow", "MuGoldEtroL4"))
        self.pushButton_25.setText(_translate("MainWindow", "DirtyL1"))
        self.pushButton_22.setText(_translate("MainWindow", "MuGoldEtroL2"))
        self.pushButton_17.setText(_translate("MainWindow", "Upper"))
        self.pushButton_26.setText(_translate("MainWindow", "Next"))
        self.pushButton_27.setText(_translate("MainWindow", "Source File"))
        self.pushButton_33.setText(_translate("MainWindow", "Destination file"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))

